/**
 * Generated from Java file for CustomNPC+ Minecraft Mod 1.7.10
 * Package: noppes.npcs.api.entity
 */

export interface ICustomNpc extends IEntityLiving<T>, IAnimatable {

    // Methods
    getSize(): number;
    setSize(size: number): void;
    getModelType(): number;
    setModelType(modelType: number): void;
    getName(): string;
    setRotation(rotation: number): void;
    setRotationType(rotationType: number): void;
    getRotationType(): number;
    setMovingType(movingType: number): void;
    getMovingType(): number;
    setName(name: string): void;
    getTitle(): string;
    setTitle(title: string): void;
    getTexture(): string;
    setTexture(texture: string): void;
    getHome(): import('../IPos').IPos;
    getHomeX(): number;
    setHomeX(x: number): void;
    getHomeY(): number;
    setHomeY(y: number): void;
    getHomeZ(): number;
    setHomeZ(z: number): void;
    setHome(x: number, y: number, z: number): void;
    setHome(pos: import('../IPos').IPos): void;
    setMaxHealth(health: number): void;
    setReturnToHome(bo: boolean): void;
    getReturnToHome(): boolean;
    getFaction(): import('../handler/data/IFaction').IFaction;
    setFaction(id: number): void;
    setAttackFactions(attackOtherFactions: boolean): void;
    getAttackFactions(): boolean;
    setDefendFaction(defendFaction: boolean): void;
    getDefendFaction(): boolean;
    getType(): number;
    typeOf(type: number): boolean;
    shootItem(target: IEntityLivingBase, item: import('../item/IItemStack').IItemStack, accuracy: number): void;
    setProjectilesKeepTerrain(b: boolean): void;
    getProjectilesKeepTerrain(): boolean;
    say(message: string): void;
    say(player: import('./IPlayer').IPlayer, message: string): void;
    getDialog(slot: number): import('../handler/data/IDialog').IDialog;
    getDialogId(slot: number): number;
    setDialog(slot: number, dialog: import('../handler/data/IDialog').IDialog): void;
    setDialog(slot: number, dialogId: number): void;
    getInteractLines(): import('../handler/data/ILines').ILines;
    getWorldLines(): import('../handler/data/ILines').ILines;
    getAttackLines(): import('../handler/data/ILines').ILines;
    getKilledLines(): import('../handler/data/ILines').ILines;
    getKillLines(): import('../handler/data/ILines').ILines;
    kill(): void;
    reset(): void;
    getAnimationData(): import('../handler/data/IAnimationData').IAnimationData;
    getRole(): import('../roles/IRole').IRole;
    setRole(role: number): void;
    getJob(): import('../jobs/IJob').IJob;
    setJob(job: number): void;
    getRightItem(): import('../item/IItemStack').IItemStack;
    setRightItem(item: import('../item/IItemStack').IItemStack): void;
    getLefttItem(): import('../item/IItemStack').IItemStack;
    getLeftItem(): import('../item/IItemStack').IItemStack;
    setLeftItem(item: import('../item/IItemStack').IItemStack): void;
    getProjectileItem(): import('../item/IItemStack').IItemStack;
    setProjectileItem(item: import('../item/IItemStack').IItemStack): void;
    canAimWhileShooting(): boolean;
    aimWhileShooting(aimWhileShooting: boolean): void;
    setAimType(aimWhileShooting: byte): void;
    getAimType(): byte;
    setMinProjectileDelay(minDelay: number): void;
    getMinProjectileDelay(): number;
    setMaxProjectileDelay(maxDelay: number): void;
    getMaxProjectileDelay(): number;
    setRangedRange(rangedRange: number): void;
    getRangedRange(): number;
    setFireRate(rate: number): void;
    getFireRate(): number;
    setBurstCount(burstCount: number): void;
    getBurstCount(): number;
    setShotCount(shotCount: number): void;
    getShotCount(): number;
    setAccuracy(accuracy: number): void;
    getAccuracy(): number;
    getFireSound(): string;
    setFireSound(fireSound: string): void;
    getArmor(slot: number): import('../item/IItemStack').IItemStack;
    setArmor(slot: number, item: import('../item/IItemStack').IItemStack): void;
    getLootItem(slot: number): import('../item/IItemStack').IItemStack;
    setLootItem(slot: number, item: import('../item/IItemStack').IItemStack): void;
    getLootChance(slot: number): number;
    setLootChance(slot: number, chance: number): void;
    getLootMode(): number;
    setLootMode(lootMode: number): void;
    setMinLootXP(lootXP: number): void;
    setMaxLootXP(lootXP: number): void;
    getMinLootXP(): number;
    getMaxLootXP(): number;
    getCanDrown(): boolean;
    setDrowningType(type: number): void;
    canBreathe(): boolean;
    setAnimation(type: number): void;
    setTacticalVariant(variant: number): void;
    getTacticalVariant(): number;
    setTacticalVariant(variant: string): void;
    getTacticalVariantName(): string;
    getCombatPolicyName(): string;
    setCombatPolicy(policy: number): void;
    getCombatPolicy(): number;
    setCombatPolicy(policy: string): void;
    setTacticalRadius(tacticalRadius: number): void;
    getTacticalRadius(): number;
    setIgnoreCobweb(ignore: boolean): void;
    getIgnoreCobweb(): boolean;
    setOnFoundEnemy(onAttack: number): void;
    onFoundEnemy(): number;
    setShelterFrom(shelterFrom: number): void;
    getShelterFrom(): number;
    hasLivingAnimation(): boolean;
    setLivingAnimation(livingAnimation: boolean): void;
    setVisibleType(type: number): void;
    getVisibleType(): number;
    setVisibleTo(player: import('./IPlayer').IPlayer, visible: boolean): void;
    isVisibleTo(player: import('./IPlayer').IPlayer): boolean;
    setShowName(type: number): void;
    getShowName(): number;
    getShowBossBar(): number;
    setShowBossBar(type: number): void;
    getMeleeStrength(): number;
    setMeleeStrength(strength: number): void;
    getMeleeSpeed(): number;
    setMeleeSpeed(speed: number): void;
    getMeleeRange(): number;
    setMeleeRange(range: number): void;
    getSwingWarmup(): number;
    setSwingWarmup(ticks: number): void;
    getKnockback(): number;
    setKnockback(knockback: number): void;
    getAggroRange(): number;
    setAggroRange(aggroRange: number): void;
    getRangedStrength(): number;
    setRangedStrength(strength: number): void;
    getRangedSpeed(): number;
    setRangedSpeed(speed: number): void;
    getRangedBurst(): number;
    setRangedBurst(count: number): void;
    getRespawnTime(): number;
    setRespawnTime(time: number): void;
    getRespawnCycle(): number;
    setRespawnCycle(cycle: number): void;
    getHideKilledBody(): boolean;
    hideKilledBody(hide: boolean): void;
    naturallyDespawns(): boolean;
    setNaturallyDespawns(canDespawn: boolean): void;
    spawnedFromSoulStone(): boolean;
    getSoulStonePlayerName(): string;
    isSoulStoneInit(): boolean;
    getRefuseSoulStone(): boolean;
    setRefuseSoulStone(refuse: boolean): void;
    getMinPointsToSoulStone(): number;
    setMinPointsToSoulStone(points: number): void;
    giveItem(player: import('./IPlayer').IPlayer, item: import('../item/IItemStack').IItemStack): void;
    executeCommand(command: string): void;
    getModelData(): import('./data/IModelData').IModelData;
    setHeadScale(x: number, y: number, z: number): void;
    setBodyScale(x: number, y: number, z: number): void;
    setArmsScale(x: number, y: number, z: number): void;
    setLegsScale(x: number, y: number, z: number): void;
    setExplosionResistance(resistance: number): void;
    getExplosionResistance(): number;
    setMeleeResistance(resistance: number): void;
    getMeleeResistance(): number;
    setArrowResistance(resistance: number): void;
    getArrowResistance(): number;
    setKnockbackResistance(resistance: number): void;
    getKnockbackResistance(): number;
    setRetaliateType(type: number): void;
    getCombatRegen(): number;
    setCombatRegen(regen: number): void;
    getHealthRegen(): number;
    setHealthRegen(regen: number): void;
    getAge(): number;
    getTimers(): import('../ITimers').ITimers;
    setFly(fly: number): void;
    canFly(): boolean;
    setFlySpeed(flySpeed: number): void;
    getFlySpeed(unused: number): number;
    setFlyGravity(flyGravity: number): void;
    getFlyGravity(unused: number): number;
    setFlyHeightLimit(flyHeightLimit: number): void;
    getFlyHeightLimit(unused: number): number;
    limitFlyHeight(limit: boolean): void;
    isFlyHeightLimited(unused: boolean): boolean;
    setSpeed(speed: number): void;
    getSpeed(): number;
    setSkinType(type: byte): void;
    getSkinType(): byte;
    setSkinUrl(url: string): void;
    getSkinUrl(): string;
    setCloakTexture(cloakTexture: string): void;
    getCloakTexture(): string;
    setOverlayTexture(overlayTexture: string): void;
    getOverlayTexture(): string;
    getOverlays(): import('../handler/IOverlayHandler').IOverlayHandler;
    setCollisionType(type: number): void;
    getCollisionType(): number;
    updateClient(): void;
    updateAI(): void;
    getActionManager(): import('../handler/IActionManager').IActionManager;
    getMagicData(): import('../handler/data/IMagicData').IMagicData;

}
