package noppes.npcs.constants;

import noppes.npcs.quests.QuestItem;
import noppes.npcs.roles.companion.CompanionTrader;
import noppes.npcs.scripted.ScriptBlock;

import javax.swing.border.Border;

public enum EnumGuiType {
	MainMenuDisplay,
	MainMenuInv,
	MainMenuStats,
	ManageFactions,
	ManageTags,
    ManageCustomForms,
    ManageCustomAuras,
	ManageAnimations,
	MainMenuAdvanced,
	MainMenuGlobal,
	PlayerBankSmall,
	PlayerFollowerHire,
	PlayerFollower,
	SetupItemGiver,
	SetupTrader,
	SetupFollower,
	PlayerTrader,
	PlayerTransporter,
	RedstoneBlock,
	SetupTransporter,
	ManageTransport,
	ManageBanks,
    Cloner,
	SetupBank,
	ManageDialogs,
	ManageQuests,
    PlayerCarpentryBench,
    PlayerAnvil,
	QuestReward,
	ManageRecipes,
    ManageEffects,
	QuestItem,
	NpcRemote,
    GlobalRemote,
	ScriptEvent,
	MoneyBag,
	MainMenuAI,
	MovingPath,
	PlayerBankUnlock,
	PlayerBankUprade,
	PlayerBankLarge,
	MobSpawnerAdd,
	PlayerMailbox,
	PlayerMailman,
	Waypoint,
	MerchantAdd,
	MobSpawnerMounter,
	Crate,
	NpcDimensions,
	Border,
	BigSign,
	Script,
	Companion,
	CompanionInv,
	CompanionTalent,
	CompanionTrader,
	ManageLinked,
	CustomGui,
	ScriptItem,
	ScriptBlock;
}
