package
noppes.npcs.constants;

public enum EnumPacketClient {
	GUI_REDSTONE,
	GUI_WAYPOINT,
	GUI_DATA,
	VILLAGER_LIST,
	CLONE,
    TELEPORTER,
	OPEN_BOOK,
	ISGUIOPEN,
    SCRIPT_OVERLAY_DATA,
	SCRIPT_OVERLAY_CLOSE,
	SWING_PLAYER_ARM,
	PLAYER_UPDATE_SKIN_OVERLAYS,
	UPDATE_ANIMATIONS,
	OVERLAY_QUEST_TRACKING,
	DISABLE_MOUSE_INPUT,
	SYNC_WEAPON,
    MARK_DATA,
    PARTY_DATA
}
