/**
 * Generated from Java file for CustomNPC+ Minecraft Mod 1.7.10
 * Package: noppes.npcs.api
 */

export class AbstractNpcAPI {

    // Methods
    Instance(): AbstractNpcAPI;
    IsAvailable(): boolean;
    getTempData(key: string): any;
    setTempData(key: string, value: any): void;
    hasTempData(key: string): boolean;
    removeTempData(key: string): void;
    clearTempData(): void;
    getTempDataKeys(): string[];
    getStoredData(key: string): any;
    setStoredData(key: string, value: any): void;
    hasStoredData(key: string): boolean;
    removeStoredData(key: string): void;
    clearStoredData(): void;
    getStoredDataKeys(): string[];
    registerICommand(command: import('./ICommand').ICommand): void;
    getICommand(commandName: string, priorityLevel: number): import('./ICommand').ICommand;
    addGlobalObject(key: string, obj: any): void;
    removeGlobalObject(key: string): void;
    hasGlobalObject(key: string): boolean;
    getEngineObjects(): Record<string, any>;
    sizeOfObject(obj: any): number;
    stopServer(): void;
    getCurrentPlayerCount(): number;
    getMaxPlayers(): number;
    kickAllPlayers(): void;
    isHardcore(): boolean;
    getFile(path: string): import('../../../java/io/File').File;
    getServerOwner(): string;
    getFactions(): import('./handler/IFactionHandler').IFactionHandler;
    getRecipes(): import('./handler/IRecipeHandler').IRecipeHandler;
    getQuests(): import('./handler/IQuestHandler').IQuestHandler;
    getDialogs(): import('./handler/IDialogHandler').IDialogHandler;
    getClones(): import('./handler/ICloneHandler').ICloneHandler;
    getNaturalSpawns(): import('./handler/INaturalSpawnsHandler').INaturalSpawnsHandler;
    getProfileHandler(): import('./handler/IProfileHandler').IProfileHandler;
    getCustomEffectHandler(): import('./handler/ICustomEffectHandler').ICustomEffectHandler;
    getMagicHandler(): import('./handler/IMagicHandler').IMagicHandler;
    getPartyHandler(): import('./handler/IPartyHandler').IPartyHandler;
    getLocations(): import('./handler/ITransportHandler').ITransportHandler;
    getAnimations(): import('./handler/IAnimationHandler').IAnimationHandler;
    getAllBiomeNames(): string[];
    createNPC(world: import('./IWorld').IWorld): import('./entity/ICustomNpc').ICustomNpc;
    spawnNPC(world: import('./IWorld').IWorld, x: number, y: number, z: number): import('./entity/ICustomNpc').ICustomNpc;
    spawnNPC(world: import('./IWorld').IWorld, pos: import('./IPos').IPos): import('./entity/ICustomNpc').ICustomNpc;
    getIEntity(entity: any): import('./entity/IEntity').IEntity;
    getPlayer(username: string): import('./entity/IPlayer').IPlayer;
    getChunkLoadingNPCs(): import('./entity/ICustomNpc').ICustomNpc[];
    getLoadedEntities(): import('./entity/IEntity').IEntity[];
    getIBlock(world: import('./IWorld').IWorld, x: number, y: number, z: number): import('./IBlock').IBlock;
    getIBlock(world: import('./IWorld').IWorld, pos: import('./IPos').IPos): import('./IBlock').IBlock;
    getITileEntity(world: import('./IWorld').IWorld, pos: import('./IPos').IPos): import('./ITileEntity').ITileEntity;
    getITileEntity(world: import('./IWorld').IWorld, x: number, y: number, z: number): import('./ITileEntity').ITileEntity;
    getITileEntity(tileEntity: any): import('./ITileEntity').ITileEntity;
    getIPos(pos: any): import('./IPos').IPos;
    getIPos(x: number, y: number, z: number): import('./IPos').IPos;
    getIPos(serializedPos: number): import('./IPos').IPos;
    getAllInBox(from: import('./IPos').IPos, to: import('./IPos').IPos, sortByDistance: boolean): import('./IPos').IPos[];
    getAllInBox(from: import('./IPos').IPos, to: import('./IPos').IPos): import('./IPos').IPos[];
    getIContainer(inventory: any): import('./IContainer').IContainer;
    getIItemStack(itemStack: any): import('./item/IItemStack').IItemStack;
    getIWorld(world: any): import('./IWorld').IWorld;
    getIWorld(dimensionId: number): import('./IWorld').IWorld;
    getIWorldLoad(dimensionId: number): import('./IWorld').IWorld;
    getActionManager(): import('./handler/IActionManager').IActionManager;
    getIWorlds(): import('./IWorld').IWorld[];
    getIDamageSource(damageSource: any): import('./IDamageSource').IDamageSource;
    getIDamageSource(entity: import('./entity/IEntity').IEntity): import('./IDamageSource').IDamageSource;
    events(): import('../../../cpw/mods/fml/common/eventhandler/EventBus').EventBus;
    getGlobalDir(): import('../../../java/io/File').File;
    getWorldDir(): import('../../../java/io/File').File;
    executeCommand(world: import('./IWorld').IWorld, command: string): void;
    getRandomName(dictionary: number, gender: number): string;
    getINbt(nbt: any): import('./INbt').INbt;
    stringToNbt(str: string): import('./INbt').INbt;
    getAllServerPlayers(): import('./entity/IPlayer').IPlayer[];
    getPlayerNames(): string[];
    createItemFromNBT(nbt: import('./INbt').INbt): import('./item/IItemStack').IItemStack;
    createItem(id: string, damage: number, size: number): import('./item/IItemStack').IItemStack;
    playSoundAtEntity(entity: import('./entity/IEntity').IEntity, sound: string, volume: number, pitch: number): void;
    playSoundToNearExcept(player: import('./entity/IPlayer').IPlayer, sound: string, volume: number, pitch: number): void;
    getMOTD(): string;
    setMOTD(motd: string): void;
    createParticle(directory: string): import('./IParticle').IParticle;
    createEntityParticle(directory: string): import('./IParticle').IParticle;
    createSound(directory: string): import('./handler/data/ISound').ISound;
    playSound(id: number, sound: import('./handler/data/ISound').ISound): void;
    playSound(sound: import('./handler/data/ISound').ISound): void;
    stopSound(id: number): void;
    pauseSounds(): void;
    continueSounds(): void;
    stopSounds(): void;
    getServerTime(): number;
    arePlayerScriptsEnabled(): boolean;
    areForgeScriptsEnabled(): boolean;
    areGlobalNPCScriptsEnabled(): boolean;
    enablePlayerScripts(enable: boolean): void;
    enableForgeScripts(enable: boolean): void;
    enableGlobalNPCScripts(enable: boolean): void;
    createCustomGui(id: number, width: number, height: number, pauseGame: boolean): import('./gui/ICustomGui').ICustomGui;
    createCustomOverlay(id: number): import('./overlay/ICustomOverlay').ICustomOverlay;
    createSkinOverlay(texture: string): import('./ISkinOverlay').ISkinOverlay;
    millisToTime(millis: number): string;
    ticksToTime(ticks: number): string;
    createAnimation(name: string): import('./handler/data/IAnimation').IAnimation;
    createAnimation(name: string, speed: number, smooth: number): import('./handler/data/IAnimation').IAnimation;
    createFrame(duration: number): import('./handler/data/IFrame').IFrame;
    createFrame(duration: number, speed: number, smooth: number): import('./handler/data/IFrame').IFrame;
    createPart(name: string): import('./handler/data/IFramePart').IFramePart;
    createPart(name: string, rotation: number[], pivot: number[]): import('./handler/data/IFramePart').IFramePart;
    createPart(name: string, rotation: number[], pivot: number[], speed: number, smooth: number): import('./handler/data/IFramePart').IFramePart;
    createPart(partId: number): import('./handler/data/IFramePart').IFramePart;
    createPart(partId: number, rotation: number[], pivot: number[]): import('./handler/data/IFramePart').IFramePart;
    createPart(partId: number, rotation: number[], pivot: number[], speed: number, smooth: number): import('./handler/data/IFramePart').IFramePart;

}
