/**
 * Generated from Java file for CustomNPC+ Minecraft Mod 1.7.10
 * Package: noppes.npcs.api
 */

export interface IWorld {

    // Methods
    getTime(): number;
    getTotalTime(): number;
    areAllPlayersAsleep(): boolean;
    getBlock(x: number, y: number, z: number): import('./IBlock').IBlock;
    getBlock(pos: import('./IPos').IPos): import('./IBlock').IBlock;
    getTopBlock(x: number, z: number): import('./IBlock').IBlock;
    getTopBlock(pos: import('./IPos').IPos): import('./IBlock').IBlock;
    isBlockFreezable(pos: import('./IPos').IPos): boolean;
    isBlockFreezable(x: number, y: number, z: number): boolean;
    isBlockFreezableNaturally(pos: import('./IPos').IPos): boolean;
    isBlockFreezableNaturally(x: number, y: number, z: number): boolean;
    canBlockFreeze(pos: import('./IPos').IPos, adjacentToWater: boolean): boolean;
    canBlockFreeze(x: number, y: number, z: number, adjacentToWater: boolean): boolean;
    canBlockFreezeBody(pos: import('./IPos').IPos, adjacentToWater: boolean): boolean;
    canBlockFreezeBody(x: number, y: number, z: number, adjacentToWater: boolean): boolean;
    canSnowAt(pos: import('./IPos').IPos, checkLight: boolean): boolean;
    canSnowAt(x: number, y: number, z: number, checkLight: boolean): boolean;
    canSnowAtBody(pos: import('./IPos').IPos, checkLight: boolean): boolean;
    canSnowAtBody(x: number, y: number, z: number, checkLight: boolean): boolean;
    getHeightValue(x: number, z: number): number;
    getHeightValue(pos: import('./IPos').IPos): number;
    getChunkHeightMapMinimum(x: number, z: number): number;
    getChunkHeightMapMinimum(pos: import('./IPos').IPos): number;
    getBlockMetadata(x: number, y: number, z: number): number;
    getBlockMetadata(pos: import('./IPos').IPos): number;
    setBlockMetadataWithNotify(x: number, y: number, z: number, metadata: number, flag: number): boolean;
    setBlockMetadataWithNotify(pos: import('./IPos').IPos, metadata: number, flag: number): boolean;
    canSeeSky(x: number, y: number, z: number): boolean;
    canSeeSky(pos: import('./IPos').IPos): boolean;
    getFullBlockLightValue(x: number, y: number, z: number): number;
    getFullBlockLightValue(pos: import('./IPos').IPos): number;
    getBlockLightValue(x: number, y: number, z: number): number;
    getBlockLightValue(pos: import('./IPos').IPos): number;
    playSoundAtEntity(entity: import('./entity/IEntity').IEntity, sound: string, volume: number, pitch: number): void;
    playSoundToNearExcept(player: import('./entity/IPlayer').IPlayer, sound: string, volume: number, pitch: number): void;
    playSound(id: number, sound: import('./handler/data/ISound').ISound): void;
    stopSound(id: number): void;
    pauseSounds(): void;
    continueSounds(): void;
    stopSounds(): void;
    getEntityByID(id: number): import('./entity/IEntity').IEntity;
    spawnEntityInWorld(entity: import('./entity/IEntity').IEntity): boolean;
    getClosestPlayerToEntity(entity: import('./entity/IEntity').IEntity, range: number): import('./entity/IPlayer').IPlayer;
    getClosestPlayer(x: number, y: number, z: number, range: number): import('./entity/IPlayer').IPlayer;
    getClosestPlayer(pos: import('./IPos').IPos, range: number): import('./entity/IPlayer').IPlayer;
    getClosestVulnerablePlayerToEntity(entity: import('./entity/IEntity').IEntity, range: number): import('./entity/IPlayer').IPlayer;
    getClosestVulnerablePlayer(x: number, y: number, z: number, range: number): import('./entity/IPlayer').IPlayer;
    getClosestVulnerablePlayer(pos: import('./IPos').IPos, range: number): import('./entity/IPlayer').IPlayer;
    countEntities(entity: import('./entity/IEntity').IEntity): number;
    getLoadedEntities(): import('./entity/IEntity').IEntity[];
    getEntitiesNear(position: import('./IPos').IPos, range: number): import('./entity/IEntity').IEntity[];
    getEntitiesNear(x: number, y: number, z: number, range: number): import('./entity/IEntity').IEntity[];
    setTileEntity(x: number, y: number, z: number, tileEntity: import('./ITileEntity').ITileEntity): void;
    setTileEntity(pos: import('./IPos').IPos, tileEntity: import('./ITileEntity').ITileEntity): void;
    removeTileEntity(x: number, y: number, z: number): void;
    removeTileEntity(pos: import('./IPos').IPos): void;
    isBlockFullCube(x: number, y: number, z: number): boolean;
    isBlockFullCube(pos: import('./IPos').IPos): boolean;
    getSeed(): number;
    setSpawnLocation(x: number, y: number, z: number): void;
    setSpawnLocation(pos: import('./IPos').IPos): void;
    canLightningStrikeAt(x: number, y: number, z: number): boolean;
    canLightningStrikeAt(pos: import('./IPos').IPos): boolean;
    isBlockHighHumidity(x: number, y: number, z: number): boolean;
    isBlockHighHumidity(pos: import('./IPos').IPos): boolean;
    getSignText(x: number, y: number, z: number): string;
    getSignText(pos: import('./IPos').IPos): string;
    setBlock(x: number, y: number, z: number, item: import('./item/IItemStack').IItemStack): boolean;
    setBlock(pos: import('./IPos').IPos, item: import('./item/IItemStack').IItemStack): boolean;
    setBlock(x: number, y: number, z: number, block: import('./IBlock').IBlock): boolean;
    setBlock(pos: import('./IPos').IPos, block: import('./IBlock').IBlock): boolean;
    removeBlock(x: number, y: number, z: number): void;
    removeBlock(pos: import('./IPos').IPos): void;
    isPlaceCancelled(posX: number, posY: number, posZ: number): boolean;
    isPlaceCancelled(pos: import('./IPos').IPos): boolean;
    isBreakCancelled(posX: number, posY: number, posZ: number): boolean;
    isBreakCancelled(pos: import('./IPos').IPos): boolean;
    rayCastPos(startPos: number[], lookVector: number[], maxDistance: number, stopOnBlock: boolean, stopOnLiquid: boolean, stopOnCollision: boolean): import('./IPos').IPos;
    rayCastPos(startPos: number[], lookVector: number[], maxDistance: number): import('./IPos').IPos;
    rayCastPos(startPos: import('./IPos').IPos, lookVector: import('./IPos').IPos, maxDistance: number, stopOnBlock: boolean, stopOnLiquid: boolean, stopOnCollision: boolean): import('./IPos').IPos;
    rayCastPos(startPos: import('./IPos').IPos, lookVector: import('./IPos').IPos, maxDistance: number): import('./IPos').IPos;
    rayCastBlock(startPos: number[], lookVector: number[], maxDistance: number, stopOnBlock: boolean, stopOnLiquid: boolean, stopOnCollision: boolean): import('./IBlock').IBlock;
    rayCastBlock(startPos: number[], lookVector: number[], maxDistance: number): import('./IBlock').IBlock;
    rayCastBlock(startPos: import('./IPos').IPos, lookVector: import('./IPos').IPos, maxDistance: number, stopOnBlock: boolean, stopOnLiquid: boolean, stopOnCollision: boolean): import('./IBlock').IBlock;
    rayCastBlock(startPos: import('./IPos').IPos, lookVector: import('./IPos').IPos, maxDistance: number): import('./IBlock').IBlock;
    getNearestAir(startPos: import('./IPos').IPos, maxHeight: number): import('./IPos').IPos;
    rayCastEntities(startPos: number[], lookVector: number[], maxDistance: number, offset: number, range: number, stopOnBlock: boolean, stopOnLiquid: boolean, stopOnCollision: boolean): import('./entity/IEntity').IEntity[];
    rayCastEntities(ignoreEntities: import('./entity/IEntity').IEntity[], startPos: number[], lookVector: number[], maxDistance: number, offset: number, range: number, stopOnBlock: boolean, stopOnLiquid: boolean, stopOnCollision: boolean): import('./entity/IEntity').IEntity[];
    rayCastEntities(startPos: import('./IPos').IPos, lookVector: import('./IPos').IPos, maxDistance: number, offset: number, range: number, stopOnBlock: boolean, stopOnLiquid: boolean, stopOnCollision: boolean): import('./entity/IEntity').IEntity[];
    rayCastEntities(startPos: number[], lookVector: number[], maxDistance: number, offset: number, range: number): import('./entity/IEntity').IEntity[];
    rayCastEntities(startPos: import('./IPos').IPos, lookVector: import('./IPos').IPos, maxDistance: number, offset: number, range: number): import('./entity/IEntity').IEntity[];
    getPlayer(name: string): import('./entity/IPlayer').IPlayer;
    getPlayerByUUID(uuid: string): import('./entity/IPlayer').IPlayer;
    setTime(time: number): void;
    isDay(): boolean;
    isRaining(): boolean;
    setRaining(bo: boolean): void;
    thunderStrike(x: number, y: number, z: number): void;
    thunderStrike(pos: import('./IPos').IPos): void;
    spawnParticle(particle: string, x: number, y: number, z: number, dx: number, dy: number, dz: number, speed: number, count: number): void;
    spawnParticle(particle: string, pos: import('./IPos').IPos, dx: number, dy: number, dz: number, speed: number, count: number): void;
    createItem(id: string, damage: number, size: number): import('./item/IItemStack').IItemStack;
    createEntityParticle(directory: string): import('./IParticle').IParticle;
    getTempData(key: string): any;
    setTempData(key: string, value: any): void;
    hasTempData(key: string): boolean;
    removeTempData(key: string): void;
    clearTempData(): void;
    getTempDataKeys(): string[];
    getStoredData(key: string): any;
    setStoredData(key: string, value: any): void;
    hasStoredData(key: string): boolean;
    removeStoredData(key: string): void;
    clearStoredData(): void;
    getStoredDataKeys(): string[];
    explode(x: number, y: number, z: number, range: number, fire: boolean, grief: boolean): void;
    explode(pos: import('./IPos').IPos, range: number, fire: boolean, grief: boolean): void;
    getAllServerPlayers(): import('./entity/IPlayer').IPlayer[];
    getPlayerNames(): string[];
    getBiomeName(x: number, z: number): string;
    getBiomeName(pos: import('./IPos').IPos): string;
    spawnClone(x: number, y: number, z: number, tab: number, name: string, ignoreProtection: boolean): import('./entity/IEntity').IEntity;
    spawnClone(pos: import('./IPos').IPos, tab: number, name: string, ignoreProtection: boolean): import('./entity/IEntity').IEntity;
    spawnClone(x: number, y: number, z: number, tab: number, name: string): import('./entity/IEntity').IEntity;
    spawnClone(pos: import('./IPos').IPos, tab: number, name: string): import('./entity/IEntity').IEntity;
    getScoreboard(): import('./scoreboard/IScoreboard').IScoreboard;
    getMCWorld(): WorldServer;
    getDimensionID(): number;
    broadcast(message: string): void;

}
