package kamkeel.npcs.fixtures;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.List;

/** Writes the README that ships beside the generated worlds. */
public final class Readme {

    private Readme() {
    }

    public static void write(File file, List<FixtureWorld> worlds, Manifest manifest) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("# CustomNPC+ fixtures\n\n");
        sb.append("Generated by `gradlew scribeFixtures` in the CustomNPC+ repository, on the\n");
        sb.append("`scribe` branch. Do not edit by hand -- regenerate.\n\n");

        sb.append("## What these are\n\n");
        sb.append("Real CustomNPC+ save data, written by CustomNPC+'s own serialization running\n");
        sb.append("against a bootstrapped-but-unlaunched Minecraft. No world was played to produce\n");
        sb.append("them and no byte here was hand-authored.\n\n");
        sb.append("That distinction is the whole point. A hand-written `factions.dat` asserts what\n");
        sb.append("its author believed the format to be, so a reader tested against it only proves\n");
        sb.append("it agrees with that belief. These files are evidence about the format itself.\n\n");

        sb.append("## Layout\n\n");
        sb.append("```\n");
        for (FixtureWorld world : worlds) {
            sb.append(world.name()).append("/customnpcs/    <- a CustomNPC+ world directory, and nothing else\n");
        }
        sb.append("_readable/<world>/   <- NBTJsonUtil renderings of the .dat files, for humans\n");
        sb.append("manifest.json        <- which file holds which case, and why\n");
        sb.append("```\n\n");
        sb.append("Each `<world>/` holds `customnpcs/` and nothing else, so it drops straight into\n");
        sb.append("a save directory -- or, in Scribe, works as-is as a `cnpc_data_sets` overlay.\n");
        sb.append("The readable renderings sit outside the world directories for that reason.\n\n");
        sb.append("`_readable/` is a debugging aid, not a fixture: it is CustomNPC+'s own JSON\n");
        sb.append("rendering, which suffixes scalars with their type (`5b`, `5L`, `1.0f`) and is\n");
        sb.append("therefore deliberately not strict JSON. The widths being visible is the point.\n\n");

        sb.append("## The worlds\n\n");
        for (FixtureWorld world : worlds) {
            sb.append("- **`").append(world.name()).append("`** -- ").append(world.purpose()).append("\n");
        }
        sb.append("\n");

        sb.append("## Two formats, not one\n\n");
        sb.append("- **`.dat`** -- gzipped NBT, written with `CompressedStreamTools`. Factions,\n");
        sb.append("  custom effects, recipes, magic, animations, linked items, tags, and the rest.\n");
        sb.append("- **Dialogs and quests are not `.dat`.** They are `NBTJsonUtil` text files at\n");
        sb.append("  `customnpcs/dialogs/<category>/<id>.json`. The directory *is* the category and\n");
        sb.append("  the filename *is* the id -- neither appears inside the file, because\n");
        sb.append("  `saveDialog` writes `writeToNBTPartial`, which omits `DialogId`.\n\n");

        sb.append("## Reproducibility\n\n");
        sb.append("Regenerating produces byte-identical output, with the exceptions below. Those\n");
        sb.append("are properties of CustomNPC+'s writers, not of this generator.\n\n");
        for (String warning : manifest.warnings()) {
            sb.append("- ").append(warning).append("\n");
        }
        sb.append("\n");

        sb.append("## Totals\n\n");
        sb.append("`").append(manifest.count()).append("` files: ");
        sb.append(manifest.countOf("dialog")).append(" dialogs, ");
        sb.append(manifest.countOf("quest")).append(" quests, ");
        sb.append(manifest.count() - manifest.countOf("dialog") - manifest.countOf("quest"));
        sb.append(" other documents.\n");

        Writer out = new OutputStreamWriter(new FileOutputStream(file), "UTF-8");
        try {
            out.write(sb.toString());
        } finally {
            out.close();
        }
    }
}
